DROP TABLE IF EXISTS TEMPLATE_EDITS;

CREATE TABLE TEMPLATE_EDITS (
  TEMPLATE_EDIT_UID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  TEST_STEP_UID INTEGER NOT NULL,
  JSON_TEMPLATE_UID INTEGER NOT NULL,
  FIELD VARCHAR(50) NOT NULL,
  VALUE VARCHAR(2000) NULL,
  FOREIGN KEY(TEST_STEP_UID) REFERENCES TEST_STEPS(TEST_STEP_UID),
  FOREIGN KEY(JSON_TEMPLATE_UID) REFERENCES JSON_TEMPLATES(JSON_TEMPLATE_UID)
);

INSERT INTO TEMPLATE_EDITS (TEST_STEP_UID, JSON_TEMPLATE_UID, FIELD, VALUE)
    VALUES (1, 2, 'cpf', '1234567');
INSERT INTO TEMPLATE_EDITS (TEST_STEP_UID, JSON_TEMPLATE_UID, FIELD, VALUE)
    VALUES (1, 2, 'password', '88888888');
INSERT INTO TEMPLATE_EDITS (TEST_STEP_UID, JSON_TEMPLATE_UID, FIELD, VALUE)
    VALUES (2, 2, 'birthplace', null);
INSERT INTO TEMPLATE_EDITS (TEST_STEP_UID, JSON_TEMPLATE_UID, FIELD, VALUE)
    VALUES (3, 4, 'cpf', '1234567');
INSERT INTO TEMPLATE_EDITS (TEST_STEP_UID, JSON_TEMPLATE_UID, FIELD, VALUE)
    VALUES (3, 4, 'password', '88888888');
INSERT INTO TEMPLATE_EDITS (TEST_STEP_UID, JSON_TEMPLATE_UID, FIELD, VALUE)
    VALUES (3, 4, 'riskScore', '900');
INSERT INTO TEMPLATE_EDITS (TEST_STEP_UID, JSON_TEMPLATE_UID, FIELD, VALUE)
    VALUES (4, 3, 'amount', '100');