DROP TABLE IF EXISTS TEST_STEPS;

CREATE TABLE TEST_STEPS (
  TEST_STEP_UID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  TEST_SUITE_UID INTEGER NOT NULL,
  TEST_STEP_NAME VARCHAR(50) NOT NULL,
  JSON_TEMPLATE_UID INTEGER NOT NULL,
  FOREIGN KEY(TEST_SUITE_UID) REFERENCES TEST_SUITES(TEST_SUITE_UID),
  FOREIGN KEY(JSON_TEMPLATE_UID) REFERENCES JSON_TEMPLATES(JSON_TEMPLATE_UID)
);

INSERT INTO TEST_STEPS (TEST_SUITE_UID, TEST_STEP_NAME, JSON_TEMPLATE_UID)
    VALUES (1, 'Login', 5);
INSERT INTO TEST_STEPS (TEST_SUITE_UID, TEST_STEP_NAME, JSON_TEMPLATE_UID)
VALUES (1, 'Customer Profile Update', 2);
INSERT INTO TEST_STEPS (TEST_SUITE_UID, TEST_STEP_NAME, JSON_TEMPLATE_UID)
VALUES (2, 'Login', 5);
INSERT INTO TEST_STEPS (TEST_SUITE_UID, TEST_STEP_NAME, JSON_TEMPLATE_UID)
VALUES (3, 'Assets', 3);