DROP TABLE IF EXISTS TEST_SUITES;

CREATE TABLE TEST_SUITES (
  TEST_SUITE_UID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  TEST_SUITE_NAME VARCHAR(50) NOT NULL
);

INSERT INTO TEST_SUITES(TEST_SUITE_NAME)
VALUES ('Onboarding Regular Customer');
INSERT INTO TEST_SUITES(TEST_SUITE_NAME)
VALUES ('Onboarding Rejected Customer');
INSERT INTO TEST_SUITES(TEST_SUITE_NAME)
VALUES ('Create Vaquinhas');